### ISSUE TITLE
required=True in .add_argument() causes error when value is defined via config file

### ISSUE THREAD

**Issue by timvaillancourt** [kampka/yconf#3]
Similar to #2, when a arg marked 'required=True' is undefined on the command line but is defined in the config file (-c/--config), argparse will die saying "X is required".

An example yaml config _(test.yml)_:

```
production:
  db:
    port: 27018
    host: conf.test.com
```

An example BaseConfiguration class _(in test.py)_:

```
class ConfigParser(BaseConfiguration):
	def makeParser(self):
		parser = super(ConfigParser, self).makeParser()
		parser.add_argument("-L", "-logging.logLevel", dest="logging.logLevel", help="Debug level")
		parser.add_argument("-H", "-db.host", dest="db.host", help="DB Host", default='localhost', required=True)
		parser.add_argument("-P", "-db.port", dest="db.port", help="DB Port", type=int, default=27017)
		return parser
```

The following execution causes the "is required" error _(although 'db.host' is defined, just in the yaml file config)_:

```
$ python test.py -c test.yml
usage: test.py [-h] [-c CONFIGPATH] [-e {production,staging,development}]
               [-L LOGGING.LOGLEVEL] -H DB.HOST [-P DB.PORT]
test.py: error: argument -H/-db.host is required
```

Thanks again!

**Comment by kampka** [comment]
Sorry, I'll have to close this as Won't Fix.
argparse does not check the provided namespace for provided destinations and it's also not modular enough to extend it easily.

You could file this as a feature request for argparse.
Personally I'd consider it reasonable behavior.

I am also open to adding config validation that verifies the evaluation of yconf instead of only the parsed command line arguments.
If that would fix the issue for you, feel free to open a new issue.

**Comment by timvaillancourt** [comment]
Thanks @kampka, yeah I see what you mean. If argparse checked the provided namespace that would work, or maybe a callback? I'll submit a feature request for that sometime soon.

For now in one use case I've wrapped yconf and checked if the keys are defined, so if yconf could have additional support to do something similar (above argparse) that would definitely  resolve my issue and I would just avoid ever setting 'required=' in .add_argument().
